# Generated by Django 4.1.4 on 2022-12-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('amount', models.FloatField(verbose_name='amount')),
                ('items', models.JSONField(default=list, verbose_name='items')),
                ('customer', models.JSONField(default=dict, verbose_name='customer')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
