# Generated by Django 4.1.4 on 2022-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.JSONField(default=dict),
        ),
    ]
