# Generated by Django 4.1.4 on 2022-12-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_comment',
            field=models.TextField(blank=True, null=True, verbose_name='related comment'),
        ),
    ]
