# Generated by Django 4.1.4 on 2022-12-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_comment_related_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='related_comment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='related comment id'),
        ),
    ]
