# Generated by Django 4.1.4 on 2022-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_arabic',
            field=models.TextField(blank=True, null=True, verbose_name='description arabic'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_arabic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name arabic'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_arabic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='short description arabic'),
        ),
    ]
